# Generated by Django 4.2 on 2025-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardevice',
            name='capacity_kWp',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
