# Generated by Django 4.2 on 2025-08-27 13:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0002_alter_solardevice_capacity_kwp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='webp', keep_meta=True, null=True, quality=100, scale=None, size=[200, 200], upload_to='logo')),
                ('is_immediate_connection', models.BooleanField(default=True)),
            ],
        ),
    ]
