# Generated by Django 4.2 on 2025-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0003_inverterbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterbrand',
            name='is_immediate_connection',
            field=models.BooleanField(default=False),
        ),
    ]
