# Generated by Django 4.2 on 2025-08-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0004_alter_inverterbrand_is_immediate_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverterbrand',
            old_name='logo',
            new_name='logo_pic',
        ),
    ]
