# Generated by Django 4.2 on 2025-08-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0006_alter_inverterbrand_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterbrand',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
