# Generated by Django 4.2 on 2025-08-28 19:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0007_alter_inverterbrand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterbrand',
            name='logo_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='webp', keep_meta=True, null=True, quality=100, scale=None, size=[300, 300], upload_to='logo_pics'),
        ),
    ]
