# Generated by Django 4.2 on 2025-08-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0008_alter_inverterbrand_logo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100)),
                ('capacity_kwp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inverterbrand', to='DeviceInverter.inverterbrand')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inverters', to='DeviceInverter.solardevice')),
            ],
        ),
    ]
