# Generated by Django 4.2 on 2025-08-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0009_inverter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('country', models.CharField(choices=[('MY', 'Malaysia'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('IN', 'India')], default='MY', max_length=20)),
                ('province', models.CharField(choices=[('JOH', 'Johor'), ('KED', 'Kedah'), ('SEL', 'Selangor'), ('PEN', 'Penang')], max_length=20)),
                ('postal_code', models.CharField(max_length=8)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_device', to='DeviceInverter.solardevice')),
            ],
        ),
    ]
