# Generated by Django 4.2 on 2025-08-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInverter', '0010_devicelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='country',
            field=models.CharField(choices=[('Malaysia', 'Malaysia'), ('Singapore', 'Singapore'), ('Thailand', 'Thailand'), ('India', 'India')], default='MY', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='province',
            field=models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Selangor', 'Selangor'), ('Penang', 'Penang')], max_length=20),
        ),
        migrations.CreateModel(
            name='GenerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('kwp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation', to='DeviceInverter.solardevice')),
            ],
        ),
    ]
