# Generated by Django 4.2 on 2025-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_nric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nric_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
