# Generated by Django 4.2.3 on 2025-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
