# Generated by Django 4.2 on 2025-08-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('UCB', 'UCB'), ('NRBC', 'NRBC'), ('City', 'City'), ('Dhaka Bank', 'Dhaka Bank')], max_length=100)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account'), ('Fixed Deposit Account', 'Fixed Deposit Account')], max_length=100)),
                ('branch_name_code', models.CharField(max_length=100)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='accounts.useraccount')),
            ],
        ),
    ]
