# Generated by Django 4.2 on 2025-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='nric_number',
            field=models.CharField(default='11111111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='phone',
            field=models.CharField(default='00000000000', max_length=15),
            preserve_default=False,
        ),
    ]
