# Generated by Django 4.2 on 2025-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_useraccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
