# Generated by Django 4.2 on 2025-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useraccount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20, null=True),
        ),
    ]
